# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GINGER
author: GINGER
author_link: https://brainginger.github.io
author_description: Ginger
email: landy51223@yahoo.com.tw
description: > # this means to ignore newlines until "baseurl:"
  Ginger's resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainginger.github.io/" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: true

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
# highlighter:        rouge
# kramdown:
#   auto_ids:         true
#   footnote_nr:      1
#   entity_output:    as_char
#   toc_levels:       1..6
#   enable_coderay:   false
permalink: pretty

# Pagination
paginate: 1

# Sass
sass:
    style: :compressed

exclude: [Gemfile, Gemfile.lock, vendor, CNAME, LICENSE, Rakefile]
